import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const archipelagoDir = path.resolve(__dirname)
const islandsRoot = path.resolve(archipelagoDir, "../islands")
const outputFile = path.resolve(
  archipelagoDir,
  "registry.generated.js"
)
const lazy = false

function walk(dir) {
  if (!fs.existsSync(dir)) {
    return []
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true })
  const files = []

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...walk(fullPath))
      continue
    }

    if (!entry.isFile()) {
      continue
    }

    if (!/\.(jsx?|tsx?)$/.test(entry.name)) {
      continue
    }

    if (entry.name.endsWith(".d.ts")) {
      continue
    }

    files.push(fullPath)
  }

  return files
}

function toPascalCase(value) {
  return value
    .split(/[_-]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("")
}

function componentNameFromRelative(relativeWithoutExt) {
  const parts = relativeWithoutExt.split(path.sep).filter(Boolean)
  return parts.map(toPascalCase).join("__")
}

const islandFiles = walk(islandsRoot).sort()

const imports = []
const registryRows = []

if (lazy) {

  imports.push("import { defineIslandLoader } from \"@archipelago-js/react\"")


  islandFiles.forEach((absolutePath) => {
    const relativeFromIslands = path.relative(islandsRoot, absolutePath)
    const relativeWithoutExt = relativeFromIslands.replace(/\.[^.]+$/, "")
    const importPath = `../islands/${relativeWithoutExt.split(path.sep).join("/")}`
    const componentName = componentNameFromRelative(relativeWithoutExt)

    registryRows.push(`  "${componentName}": defineIslandLoader(() => import("${importPath}"))`)
  })
} else {
  islandFiles.forEach((absolutePath, index) => {
    const relativeFromIslands = path.relative(islandsRoot, absolutePath)
    const relativeWithoutExt = relativeFromIslands.replace(/\.[^.]+$/, "")
    const importPath = `../islands/${relativeWithoutExt.split(path.sep).join("/")}`
    const componentName = componentNameFromRelative(relativeWithoutExt)
    const importName = `Island${index + 1}`

    imports.push(`import ${importName} from "${importPath}"`)
    registryRows.push(`  "${componentName}": ${importName}`)
  })
}

const source = [
  "// This file is auto-generated by app/javascript/archipelago/generate_registry.mjs.",
  "// Do not edit manually.",
  "",
  ...imports,
  imports.length > 0 ? "" : "",

  "const registry = {",

  ...registryRows,
  "}",
  "",
  "export default registry",
  ""
].join("\n")

fs.writeFileSync(outputFile, source, "utf8")
