import type { IslandRegistry } from "@archipelago-js/react"

// Auto-generated by Archipelago. Run `yarn archipelago:registry` to refresh.
const registry: IslandRegistry = {}

export default registry
